version: 2.1

jobs:
  build:
    docker:
      - image: 'circleci/golang:latest'
    steps:
      - checkout
      - run: GOPATH=$PWD go get github.com/nattofriends/yomichan-import
      - run: curl -O http://ftp.monash.edu/pub/nihongo/JMdict_e.gz
      - run: gunzip JMdict_e.gz
      - run: bin/yomichan-import -format edict -title "JMdict $(date +%Y-%m-%d)" JMdict_e JMdict_e.zip
      - store_artifacts:
          path: JMdict_e.zip

workflows:
  version: 2
  commit:
    jobs:
      - build
  periodic:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
