# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * 1'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Download yomichan-import
      run: |
        curl -LO https://github.com/FooSoft/yomichan-import/releases/download/21.12.14.0/yomichan-import_linux.tar.gz
        tar xzvf yomichan-import_linux.tar.gz

    - name: Download JMdict
      run: |
        curl -LO http://ftp.edrdg.org/pub/Nihongo/JMdict_e.gz
        gunzip JMdict_e.gz
  
    - name: Convert JMdict
      run: |
        yomichan-import/yomichan -format edict -title "JMdict $(date +%Y-%m-%d)" JMdict_e JMdict_e.zip

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: JMdict_e.zip
        asset_name: JMdict_e.zip
        tag: release-holder
        overwrite: true
        body: "Built from run $GITHUB_RUN_ID"
